language: php

php:
  - 7.1
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - rm composer.lock
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - mysql -e 'CREATE DATABASE homestead;'
  - cp .env.travis .env.testing
  - cp .env.travis .env
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install

script:
  - vendor/bin/phpunit
  - npm run test

notifications:
  email: false